/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,16) MonDisParMonFuncCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdMonDisParMonFuncCmd.h"

/**
 * Start action of TC(12,16) MonDisParMonFuncCmd.
 * Set the action outcome to 'failure' if the Functional Monitoring Function
 * is supported by the application and is enabled. Otherwise set the action
 * outcome to 'success'.
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonDisParMonFuncCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsInCmdMonDisParMonFuncCmdStartAction");
   return ;
}

/**
 * Progress action of TC(12,16) MonDisParMonFuncCmd.
 * Stop the Parameter Monitoring Procedure. Set the enable status of the
 * Parameter Monitoring Function in the data pool to: 'disabled'. Set the
 * action outcome to: 'completed'.
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonDisParMonFuncCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsInCmdMonDisParMonFuncCmdProgressAction");
   return ;
}

