/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(12,26) MonRepFuncMonDefRep.
 *
 * @note This file was generated on 2018-07-14 19:50:20
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSMONREPFUNCMONDEFREP_H_
#define CRPSMONREPFUNCMONDEFREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"


/*----------------------------------------------------------------------------*/
#endif /* CRPSMONREPFUNCMONDEFREP_H */
