/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,3) MonChgTransDelCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdMonChgTransDelCmd.h"

/**
 * Start action of TC(12,3) MonChgTransDelCmd.
 * Set action outcome to 'success' if the argument of the command (the new
 * maximum reporting delay) is a positive integer; otherwise, set the outcome
 * to 'failure'
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonChgTransDelCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsInCmdMonChgTransDelCmdStartAction");
   return ;
}

/**
 * Progress action of TC(12,3) MonChgTransDelCmd.
 * Update the maximum report delay in the data pool with the value in the
 * command
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonChgTransDelCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsInCmdMonChgTransDelCmdProgressAction");
   return ;
}

