/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,24) MonDelFuncMonDefCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdMonDelFuncMonDefCmd.h"

/**
 * Start action of TC(12,24) MonDelFuncMonDefCmd.
 * Run the Command (12,24) Start Action Procedure of figure
 * \ref{fig:Cmd12s24Start}
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonDelFuncMonDefCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsInCmdMonDelFuncMonDefCmdStartAction");
   return ;
}

/**
 * Progress action of TC(12,24) MonDelFuncMonDefCmd.
 * For all functional monitors which have been accepted for execution by the
 * Start Action: remove the functional monitor from the FMDL Increment the
 * data pool variable representing the number of remaining available
 * functional monitors by the number of deleted functional monitors. Set the
 * action outcome to 'completed'.
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonDelFuncMonDefCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsInCmdMonDelFuncMonDefCmdProgressAction");
   return ;
}

