/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,13) MonRepParMonStatCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-30 23:01:15
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSINCMDMONREPPARMONSTATCMD_H_
#define CRPSINCMDMONREPPARMONSTATCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(12,13) MonRepParMonStatCmd.
 * Attempt to retrieve an OutComponent of type (12,14) from the OutFactory
 * with a size adequate to hold the status of all currently defined parameter
 * monitors in the PMDL and set the action outcome to 'success' if the
 * operation is successful. If, instead, the OutFactory fails to return the
 * requested OutComponent generate error report OUTFACTORY_FAIL
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonRepParMonStatCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(12,13) MonRepParMonStatCmd.
 * Configure the OutComponent retrieved by the Start Action with the status of
 * all parameter monitors currently defined in the PMD and load it in the
 * OutLoader. Set action outcome to 'success' if the load operation was
 * successful and to 'failed' otherwise.
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonRepParMonStatCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSINCMDMONREPPARMONSTATCMD_H */
