/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,25) MonRepFuncMonDefCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSINCMDMONREPFUNCMONDEFCMD_H_
#define CRPSINCMDMONREPFUNCMONDEFCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(12,25) MonRepFuncMonDefCmd.
 * Run the Start Action of (12,25) Command Procedure of figure
 * \image html Cmd12s25Start.png "Start Action for Command 12,5"
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonRepFuncMonDefCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(12,25) MonRepFuncMonDefCmd.
 * Configure the (12,26) reports created by the Start Action and load them in
 * the OutLoader. Set the action outcome to 'success' if the load operation is
 * successful and to "failed' otherwise.
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonRepFuncMonDefCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSINCMDMONREPFUNCMONDEFCMD_H */
