/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,5) MonAddParMonDefCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdMonAddParMonDefCmd.h"

/* ------------------------------------------------------------------------- */
void CrPsInCmdMonAddParMonDefCmdProgressAction(FwSmDesc_t smDesc) {
    CrFwPckt_t monPckt = CrFwInCmdGetPckt(smDesc);
    CrPsNParMon_t nPmon;
    CrPsParMonId_t parMonId, valCheckParId;
    CrPsParId_t parId;

    CrFwProgressStepId_t progressStepId;
    short int rdlPos;

    /* Get the progress step identifier */
    progressStepId = CrFwInCmdGetProgressStepId(smDesc);

    /* Get the number of SIDs in the command */
    nSid = getHkEnbHkCmdN(hkPckt);

    /* Get the SID to be process in the current cycle */
    sid = getHkEnbHkCmdSID(hkPckt, progressStepId);

    /* Get the RDL slot for the argument SID */
    rdlPos = CrPsHkConfigGetRdlSlot(sid);

    /* Clear SID (if the SID is loaded in the RDL and is disabled) */
    if (rdlPos > -1)
      if (getDpHkIsEnabledItem(rdlPos) == 0)
        CrPsHkConfigClearSid(sid);

    if (rdlPos < 0) {
      setDpVerFailData(sid);
      CrFwSetSmOutcome(smDesc, VER_ILL_SID);
    }

    if (getDpHkIsEnabledItem(rdlPos) == 1) {
      setDpVerFailData(sid);
      CrFwSetSmOutcome(smDesc, VER_ENB_SID);
    }

    /* Update progress step identifier */
    progressStepId++;
    CrFwInCmdSetProgressStepId(smDesc, progressStepId);

    /* Set completion outcome */
    if (progressStepId < nSid)
      CrFwInCmdSetProgressActionCompleted(smDesc, 0);
    else
      CrFwInCmdSetProgressActionCompleted(smDesc, 1);
}



/*------------------------------------------------------------------------------------*/
void CrPsInCmdMonAddParMonDefCmdTerminationAction(FwSmDesc_t smDesc) {
    CrFwProgressStepId_t nOfFailedSteps = CrFwInCmdGetNOfProgressFailure(smDesc);
    if (nOfFailedSteps > 0) {
      setDpVerFailData(nOfFailedSteps);
      CrFwSetSmOutcome(smDesc, VER_MI_S12_FD);
    } else
      CrFwSetSmOutcome(smDesc, 1);
}
