/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,27) MonRepFuncMonStatCmd.
 *
 * @note This file was generated on 2018-07-25 18:43:06
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSMONREPFUNCMONSTATCMD_H_
#define CRPSMONREPFUNCMONSTATCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(12,27) MonRepFuncMonStatCmd.
 * Attempt to retrieve an OutComponent of type (12,28) from the OutFactory
 * with a size adequate to hold the status of all currently defined functional
 * monitors in the FMDL and set the action outcome to 'success' if the
 * operation is successful. If, instead, the OutFactory fails to return the
 * requested OutComponent generate error report OUTFACTORY_FAIL
 * @param smDesc The state machine descriptor.
 */
void CrPsMonRepFuncMonStatCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(12,27) MonRepFuncMonStatCmd.
 * Configure the OutComponent retrieved by the Start Action with the status of
 * all functional monitors currently defined in the FMDL and load it in the
 * OutLoader. Set action outcome to 'success' if the load operation was
 * successful and to 'failed' otherwise.
 * @param smDesc The state machine descriptor.
 */
void CrPsMonRepFuncMonStatCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSMONREPFUNCMONSTATCMD_H */
