/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,18) MonDisFuncMonCmd.
 *
 * @note This file was generated on 2018-07-10 22:34:00
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSMONDISFUNCMONCMD_H_
#define CRPSMONDISFUNCMONCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Progress action of TC(12,18) MonDisFuncMonCmd.
 * Set the enable status of the Functional Monitoring Function in the data
 * pool to 'disabled'. Set the action outcome to 'completed'.
 * @param smDesc The state machine descriptor.
 */
void CrPsMonDisFuncMonCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSMONDISFUNCMONCMD_H */
