/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,6) MonDelParMonDefCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdMonDelParMonDefCmd.h"
#include "CrPsMonConfig.h"
#include "Pckt/CrPsPcktMon.h"
#include "DataPool/CrPsDpMon.h"
#include "DataPool/CrPsDpVer.h"
#include "DataPool/CrPsDp.h"
#include "InCmd/CrFwInCmd.h"
#include "UtilityFunctions/CrFwUtilityFunctions.h"
#include "FwPrCore.h"

void CrPsInCmdMonDelParMonDefCmdProgressAction(FwSmDesc_t smDesc) {
    CrFwPckt_t monPckt = CrFwInCmdGetPckt(smDesc);
    CrPsNParMon_t nPmon;
    CrPsParMonId_t parMonId, nmbAvailParMon;

    CrFwProgressStepId_t progressStepId;

    /* Get the progress step identifier */
    progressStepId = CrFwInCmdGetProgressStepId(smDesc);

    /* Get the number of PMONs in the command */
    nPmon = getMonDelParMonDefCmdNParMon(monPckt);

    /* Get the PMON to be processed in the current cycle */
    parMonId = getMonDelParMonDefCmdParMonId(monPckt, progressStepId);

    /* Load the PMON ID in verFailData (just in case the step fails) */
    setDpVerFailData(parMonId);

    /* Provisionally set the action outcome to 'success' */
    CrFwSetSmOutcome(smDesc, 1);

    /* Check whether the PMON is in use */
    if (getDpMonDataItemIdItem(parMonId) == 0)
        CrFwSetSmOutcome(smDesc, VER_ILL_MON);

    /* Check legality of PMON identifier */
    if (parMonId == 0)
        CrFwSetSmOutcome(smDesc, VER_ILL_MON);

    if (parMonId > MON_N_PMON)
        CrFwSetSmOutcome(smDesc, VER_ILL_MON);

    /* Check whether the PMON is enabled */
    if (getDpMonParMonEnbStatusItem(parMonId) == ENABLED)
        CrFwSetSmOutcome(smDesc, VER_MON_ENB);

    /* TBD: Check whether the PMON belongs to an FMON */

    /* If all checks were passed, delete PMON and increment number of available PMONs */
    if (CrFwGetSmOutcome(smDesc) == 1) {
        setDpMonDataItemIdItem(parMonId, 1);
        nmbAvailParMon = getDpMonNmbAvailParMon();
        setDpMonNmbAvailParMon(nmbAvailParMon+1);
    }

    /* Update progress step identifier */
    progressStepId++;
    CrFwInCmdSetProgressStepId(smDesc, progressStepId);

    /* Set completion outcome */
    if (progressStepId < nPmon)
      CrFwInCmdSetProgressActionCompleted(smDesc, 0);
    else
      CrFwInCmdSetProgressActionCompleted(smDesc, 1);
}

