/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,8) MonRepParMonDefCmd as an incoming command.
 *
 * @note This file was generated on 2018-08-19 17:56:57
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdMonRepParMonDefCmd.h"

/**
 * Start action of TC(12,8) MonRepParMonDefCmd.
 * Run the Start Action of (12,8) Command Procedure of figure
 * \ref{fig:Cmd12s8Start}
 * @param smDesc The state machine descriptor.
 */
void CrPsMonRepParMonDefCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsMonRepParMonDefCmdStartAction");
   return ;
}

/**
 * Progress action of TC(12,8) MonRepParMonDefCmd.
 * Configure the (12,9) reports created by the Start Action and load them in
 * the OutLoader. Set the action outcome to 'success' if the load operation is
 * successful and to 'failed' otherwise.
 * @param smDesc The state machine descriptor.
 */
void CrPsMonRepParMonDefCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsMonRepParMonDefCmdProgressAction");
   return ;
}

