/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,15) MonEnbParMonFuncCmd.
 *
 * @note This file was generated on 2018-07-10 22:34:00
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsMonEnbParMonFuncCmd.h"

/**
 * Start action of TC(12,15) MonEnbParMonFuncCmd.
 * Set action outcome to 'success' if the Monitoring Function is disabled
 * (i.e. if the Monitoring Function Procedure is stopped).
 * @param smDesc The state machine descriptor.
 */
void CrPsMonEnbParMonFuncCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsMonEnbParMonFuncCmdStartAction");
   return 1;
}

/**
 * Progress action of TC(12,15) MonEnbParMonFuncCmd.
 * Start the Monitoring Function Procedure. Set service 12 parameter ServUser
 * equal to the source of this command. Set the enable status of the Parameter
 * Monitoring Function in the data pool to: 'enabled'. Set the action outcome
 * to: 'completed'.
 * @param smDesc The state machine descriptor.
 */
void CrPsMonEnbParMonFuncCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsMonEnbParMonFuncCmdProgressAction");
   return 1;
}

