/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,18) MonDisFuncMonCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdMonDisFuncMonCmd.h"

/**
 * Progress action of TC(12,18) MonDisFuncMonCmd.
 * Set the enable status of the Functional Monitoring Function in the data
 * pool to 'disabled'. Set the action outcome to 'completed'.
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdMonDisFuncMonCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsInCmdMonDisFuncMonCmdProgressAction");
   return ;
}

