/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(12,10) MonRepOutOfLimitsCmd.
 *
 * @note This file was generated on 2018-07-14 19:50:20
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSMONREPOUTOFLIMITSCMD_H_
#define CRPSMONREPOUTOFLIMITSCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(12,10) MonRepOutOfLimitsCmd.
 * Run the Start Action of (12,10) Command Procedure of figure
 * \ref{fig:Cmd12s8Start}
 * @param smDesc The state machine descriptor.
 */
void CrPsMonRepOutOfLimitsCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(12,10) MonRepOutOfLimitsCmd.
 * Attempt to load the (12,11) report created by the Start Manager in the
 * OutLoader. If the load operation is successful, set the action outcome to
 * 'completed'. Otherwise, release the (12,11) report and set the action
 * outcome to 'failed'.
 * @param smDesc The state machine descriptor.
 */
void CrPsMonRepOutOfLimitsCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSMONREPOUTOFLIMITSCMD_H */
