/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(13,16) LptUpAbortRep as an out-going report.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsOutCmpLptUpAbortRep.h"

/**
 * Update action of TM(13,16) LptUpAbortRep.
 * The large message transaction identifier is taken from parameter
 * largeMsgTransId and the failure reason is read from variable lptFailCode.
 * @param smDesc The state machine descriptor.
 */
void CrPsOutCmpLptUpAbortRepUpdateAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsOutCmpLptUpAbortRepUpdateAction");
   return ;
}
