/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(13,9) LptUpFirstCmd.
 *
 * @note This file was generated on 2018-07-10 22:34:00
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSLPTUPFIRSTCMD_H_
#define CRPSLPTUPFIRSTCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(13,9) LptUpFirstCmd.
 * The following actions are performed:
 *
 * (a) Determine the identifier of the LPT Buffer for the up-transfer by
 * computing: (x MOD LPT_N_BUF) where `x' is the Large Message Transaction
 * Identifier.
 * (b) Set action outcome to 'success' if the Part Sequence Number is equal to
 * 1 and the LPT State Machine is in state INACTIVE; otherwise set the action
 * outcome to `failure'
 * @param smDesc The state machine descriptor.
 */
void CrPsLptUpFirstCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(13,9) LptUpFirstCmd.
 * The following actions are performed:
 *
 * (a) Send command StartUpTransfer to LPT State Machine
 * (b) Copy the up-transfer data to LPT Buffer and set lptSize to be equal to
 * the amout of copied data
 * (c) Set lptTime to the current time; set partSeqNmb to 1
 * (d) Set lptSrc to the source of the command
 * (e) Set the action outcome to: 'completed'
 * @param smDesc The state machine descriptor.
 */
void CrPsLptUpFirstCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSLPTUPFIRSTCMD_H */
