/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(13,130) LptAbortDownCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSINCMDLPTABORTDOWNCMD_H_
#define CRPSINCMDLPTABORTDOWNCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(13,130) LptAbortDownCmd.
 * The following actions are performed:
 *
 * (a) Determine the identifier of the LPT Buffer for the up-transfer by
 * computing: (x MOD LPT_N_BUF) where `x' is the Large Message Transaction
 * Identifier
 * (b) Set action outcome to 'success' if the LPT State Machine is in state
 * DOWN_TRANSFER; otherwise set the action outcome to `failure'
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdLptAbortDownCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(13,130) LptAbortDownCmd.
 * Send command Abort to the LPT State Machine
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdLptAbortDownCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSINCMDLPTABORTDOWNCMD_H */
