/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(13,1) LptDownFirstRep as an out-going report.
 *
 * @note This file was generated on 2018-09-30 23:01:15
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSOUTCMPLPTDOWNFIRSTREP_H_
#define CRPSOUTCMPLPTDOWNFIRSTREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Enable check of TM(13,1) LptDownFirstRep.
 * Report is enabled if the LPT State Machine is in state DOWN_TRANSFER
 * @param smDesc The state machine descriptor.
 * @return The enable check result.
 */
CrFwBool_t CrPsOutCmpLptDownFirstRepEnableCheck(FwSmDesc_t smDesc);

/**
 * Update action of TM(13,1) LptDownFirstRep.
 * The following actions are performed:
 *
 * (a) Load the first part of the large packet from the LPT Buffer
 * (b) Set the transaction identifier equal to largeMsgTransId
 * (c) Set the part number equal to partSeqNmb
 * (d) Increment partSeqNmb; and decrement lptRemSize by partSize
 * (e) Set the action outcome to: 'completed'
 * @param smDesc The state machine descriptor.
 */
void CrPsOutCmpLptDownFirstRepUpdateAction(FwSmDesc_t smDesc);

/*----------------------------------------------------------------------------*/
#endif /* CRPSOUTCMPLPTDOWNFIRSTREP_H */
