/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(3,3) HkDelHkCmd as an incoming command.
 *
 * @note This file was generated on 2018-08-19 17:56:57
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdHkDelHkCmd.h"

/**
 * Start action of TC(3,3) HkDelHkCmd.
 * Run the procedure of \image html CrPsCmd3s3Start.png "Start Action
 * of Command to Delete HK Packet" to identify the valid SIDs in the command
 * argument
 * @param smDesc The state machine descriptor.
 */
void CrPsHkDelHkCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsHkDelHkCmdStartAction");
   return ;
}

/**
 * Progress action of TC(3,3) HkDelHkCmd.
 * Delete the entries in the RDL corresponding to the SIDs which have been
 * identified as valid by the Start Action and then set the action outcome to
 * ’completed’
 * @param smDesc The state machine descriptor.
 */
void CrPsHkDelHkCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsHkDelHkCmdProgressAction");
   return ;
}

