/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(3,28) HkOneShotDiagCmd as an incoming command.
 *
 * @note This file was generated on 2018-10-28 17:05:47
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSINCMDHKONESHOTDIAGCMD_H_
#define CRPSINCMDHKONESHOTDIAGCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Ready check of TC(3,28) HkOneShotDiagCmd.
 * Return 'command is ready'
 * @param smDesc The state machine descriptor.
 * @return The ready check result.
 */
CrFwBool_t CrPsInCmdHkOneShotDiagCmdReadyCheck(FwSmDesc_t smDesc);

/**
 * Start action of TC(3,28) HkOneShotDiagCmd.
 * Run the procedure Start Action of Multi-SID Command of figure 9.3
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdHkOneShotDiagCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(3,28) HkOneShotDiagCmd.
 * Run the procedure Progress Action of Generate One-Shot Housekeeping Report
 * of figure 9.6
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdHkOneShotDiagCmdProgressAction(FwSmDesc_t smDesc);

/**
 * Termination action of TC(3,28) HkOneShotDiagCmd.
 * Set action outcome to ’success’ if all valid SIDs in the command were
 * successfully processed by the progress action; set it to ’failure’
 * otherwise
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdHkOneShotDiagCmdTerminationAction(FwSmDesc_t smDesc);

/**
 * Abort action of TC(3,28) HkOneShotDiagCmd.
 * Do nothing
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdHkOneShotDiagCmdAbortAction(FwSmDesc_t smDesc);

/*----------------------------------------------------------------------------*/
#endif /* CRPSINCMDHKONESHOTDIAGCMD_H */
