/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(3,12) HkRepStructDiagRep.
 *
 * @note This file was generated on 2018-07-14 19:50:20
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsHkRepStructDiagRep.h"

/**
 * Enable check of TM(3,12) HkRepStructDiagRep.
 * The enable status is read from the isEnabled field of the Report Definition
 * corresponding to the report’s SID
 * @param smDesc The state machine descriptor.
 * @return The enable check result.
 */
CrFwBool_t CrPsHkRepStructDiagRepEnableCheck(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsHkRepStructDiagRepEnableCheck");
   return 1;
}

/**
 * Update action of TM(3,12) HkRepStructDiagRep.
 * Load the SID definition from the RDL
 * @param smDesc The state machine descriptor.
 */
void CrPsHkRepStructDiagRepUpdateAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsHkRepStructDiagRepUpdateAction");
   return ;
}
