/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(3,7) HkEnbDiagCmd.
 *
 * @note This file was generated on 2018-07-10 22:34:00
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsHkEnbDiagCmd.h"

/**
 * Start action of TC(3,7) HkEnbDiagCmd.
 * Run the procedure Start Action of Multi-SID Command of figure
 * \image html CrPsCmd3SidStart.png "Start Action of Multi-SID
 * Command"
 * @param smDesc The state machine descriptor.
 */
void CrPsHkEnbDiagCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsHkEnbDiagCmdStartAction");
   return 1;
}

/**
 * Progress action of TC(3,7) HkEnbDiagCmd.
 * For the entries in the RDL corresponding to the SIDs which have been
 * identified as valid by the Start Action: set enabled flag to true and set
 * the cycle counter to 0. Set the action outcome to ’completed’
 * @param smDesc The state machine descriptor.
 */
void CrPsHkEnbDiagCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsHkEnbDiagCmdProgressAction");
   return 1;
}

