/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(3,8) HkDisDiagCmd.
 *
 * @note This file was generated on 2018-07-14 19:50:20
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsHkDisDiagCmd.h"

/**
 * Start action of TC(3,8) HkDisDiagCmd.
 * Run the procedure Start Action of Multi-SID Command of figure
 * \image html CrPsCmd3SidStart.png "Start Action of Multi-SID
 * Command"
 * @param smDesc The state machine descriptor.
 */
void CrPsHkDisDiagCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsHkDisDiagCmdStartAction");
   return ;
}

/**
 * Progress action of TC(3,8) HkDisDiagCmd.
 * #TM(3,60
 * @param smDesc The state machine descriptor.
 */
void CrPsHkDisDiagCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsHkDisDiagCmdProgressAction");
   return ;
}

