/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(3,26) HkDiagRep as an out-going report.
 *
 * @note This file was generated on 2019-02-16 23:53:54
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsOutCmpHkDiagRep.h"

/**
 * Ready check of TM(3,26) HkDiagRep.
 * The Ready Check performs the following actions:
 *
 * (a) If the report's cycle counter in the RDL is equal to the report's
 * period in the RDL, then the report's cycle counter in the RDL is reset to
 * zero
 * (b) If the report's cycle counter in the RDL is equal to zero and the
 * report is enabled in the RDL, then the outcome of the Ready Check is set
 * to: 'ready'; otherwise it is set to 'not ready'
 * (c) The report's cycle counter in the RDL is incremented by 1
 *
 * NB: This logic ensures that the report's cycle counter increments from zero
 * to the report's period and then is reset. The report is 'ready' when its
 * cycle counter is equal to zero. The report's cycle counter is initialized
 * to zero at application's initialization (for pre-defined reports) or when
 * the report is created (for dynamically defined commands)
 * @param smDesc The state machine descriptor.
 * @return The ready check result.
 */
CrFwBool_t CrPsOutCmpHkDiagRepReadyCheck(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsOutCmpHkDiagRepReadyCheck");
   return 1;
}

/**
 * Repeat check of TM(3,26) HkDiagRep.
 * The Repeat Check returns 'repeat' if the report's SID is defined in the
 * RDL. Otherwise it returns 'no repeat'.
 * @param smDesc The state machine descriptor.
 * @return The repeat check result.
 */
CrFwBool_t CrPsOutCmpHkDiagRepRepeatCheck(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsOutCmpHkDiagRepRepeatCheck");
   return 1;
}

/**
 * Update action of TM(3,26) HkDiagRep.
 * Load the value of the simply-commutated data items from the data pool and
 * that of the super-commutated data items from the Sampling Buffer associated
 * to the report’s SID according to the Report Definition. The report
 * definition is stored in the RDL.
 * @param smDesc The state machine descriptor.
 */
void CrPsOutCmpHkDiagRepUpdateAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsOutCmpHkDiagRepUpdateAction");
   return ;
}
