/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(3,10) HkRepStructHkRep as an out-going report.
 *
 * @note This file was generated on 2018-09-30 23:01:15
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSOUTCMPHKREPSTRUCTHKREP_H_
#define CRPSOUTCMPHKREPSTRUCTHKREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Enable check of TM(3,10) HkRepStructHkRep.
 * The enable status is read from the isEnabled field of the Report Definition
 * corresponding to the report’s SID
 * @param smDesc The state machine descriptor.
 * @return The enable check result.
 */
CrFwBool_t CrPsOutCmpHkRepStructHkRepEnableCheck(FwSmDesc_t smDesc);

/**
 * Update action of TM(3,10) HkRepStructHkRep.
 * Load the SID definition from the RDL
 * @param smDesc The state machine descriptor.
 */
void CrPsOutCmpHkRepStructHkRepUpdateAction(FwSmDesc_t smDesc);

/*----------------------------------------------------------------------------*/
#endif /* CRPSOUTCMPHKREPSTRUCTHKREP_H */
