/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(17,1) TstAreYouAliveCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-28 23:45:49
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSINCMDTSTAREYOUALIVECMD_H_
#define CRPSINCMDTSTAREYOUALIVECMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(17,1) TstAreYouAliveCmd.
 * Retrieve (17,2) report from OutFactory and set action outcome to 'success'
 * if the retrieval succeeds. If the retrieval fails, generate error report
 * OUTFACTORY FAILED and set outcome of Start Action to ’failed’ with failure
 * code VER_REP_CR_FD
 * @param smDesc The state machine descriptor.
 */
void CrPsTstAreYouAliveCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(17,1) TstAreYouAliveCmd.
 * Configure the (17,2) report with a destination equal to the source of the
 * (17,1), load it in the OutLoader, and then set the action outcome to
 * ’completed’
 * @param smDesc The state machine descriptor.
 */
void CrPsTstAreYouAliveCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSINCMDTSTAREYOUALIVECMD_H */
