/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(17,2) TstAreYouAliveRep.
 *
 * @note This file was generated on 2018-07-25 18:43:06
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSTSTAREYOUALIVEREP_H_
#define CRPSTSTAREYOUALIVEREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"


/*----------------------------------------------------------------------------*/
#endif /* CRPSTSTAREYOUALIVEREP_H */
