/**
 * @file
 * @ingroup man_tst
 *
 * Implementation of TM(17,2) TstAreYouAliveRep as an incoming report.
 * The header file for this implementation was generated by the CORDET Editor.
 */

#include "CrPsInRepTstAreYouAliveRep.h"
#include "DataPool/CrPsDpTst.h"
#include "InRep/CrFwInRep.h"
#include "Pckt/CrFwPckt.h"
#include "FwPrConfig.h"
#include "CrFwConstants.h"
#include "CrFwCmpData.h"

void CrPsInRepTstAreYouAliveRepUpdateAction(FwPrDesc_t prDesc) {
	CrFwCmpData_t* cmpData = FwPrGetData(prDesc);
	CrFwInRepData_t* inRepData = (CrFwInRepData_t*)(cmpData->cmpSpecificData);
	CrFwPckt_t pckt = inRepData->pckt;
    CrFwDestSrc_t src17s2;

    src17s2 = CrFwPcktGetSrc(pckt);
    setDpTstAreYouAliveSrc(src17s2);
    return ;
}
