/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(17,4) TstConnectRep as an out-going report.
 *
 * @note This file was generated on 2018-09-30 23:01:15
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSOUTCMPTSTCONNECTREP_H_
#define CRPSOUTCMPTSTCONNECTREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"


/*----------------------------------------------------------------------------*/
#endif /* CRPSOUTCMPTSTCONNECTREP_H */
