/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(17,4) TstConnectRep.
 *
 * @note This file was generated on 2018-07-14 19:50:20
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsTstConnectRep.h"

