/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(1,8) VerFailedTermRep.
 *
 * @note This file was generated on 2018-07-10 22:34:00
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsVerFailedTermRep.h"

/**
 * Enable check of TM(1,8) VerFailedTermRep.
 * Service 1 reports retrieve their enable status from the OurRegistry as a
 * function of their type, sub-type and discriminant
 * @param smDesc The state machine descriptor.
 * @return The enable check result.
 */
CrFwBool_t CrPsVerFailedTermRepEnableCheck(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsVerFailedTermRepEnableCheck");
   return 1;
}

