/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(1,3) VerSuccStartRep as an out-going report.
 *
 * @note This file was generated on 2018-10-28 20:42:51
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSOUTCMPVERSUCCSTARTREP_H_
#define CRPSOUTCMPVERSUCCSTARTREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"


/*----------------------------------------------------------------------------*/
#endif /* CRPSOUTCMPVERSUCCSTARTREP_H */
