/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(1,4) VerFailedStartRep as an out-going report.
 *
 * @note This file was generated on 2018-10-28 20:42:51
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSOUTCMPVERFAILEDSTARTREP_H_
#define CRPSOUTCMPVERFAILEDSTARTREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"


/*----------------------------------------------------------------------------*/
#endif /* CRPSOUTCMPVERFAILEDSTARTREP_H */
