/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(1,3) VerSuccStartRep as an out-going report.
 *
 * @note This file was generated on 2018-09-30 23:01:15
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSOUTCMPVERSUCCSTARTREP_H_
#define CRPSOUTCMPVERSUCCSTARTREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Enable check of TM(1,3) VerSuccStartRep.
 * Service 1 reports retrieve their enable status from the OutRegistry as a
 * function of their type, sub-type and discriminant
 * @param smDesc The state machine descriptor.
 * @return The enable check result.
 */
CrFwBool_t CrPsOutCmpVerSuccStartRepEnableCheck(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSOUTCMPVERSUCCSTARTREP_H */
