/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(1,3) VerSuccStartRep as an out-going report.
 *
 * @note This file was generated on 2018-08-19 17:56:57
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsOutCmpVerSuccStartRep.h"

/**
 * Enable check of TM(1,3) VerSuccStartRep.
 * Service 1 reports retrieve their enable status from the OurRegistry as a
 * function of their type, sub-type and discriminant
 * @param smDesc The state machine descriptor.
 * @return The enable check result.
 */
CrFwBool_t CrPsOutCmpVerSuccStartRepEnableCheck(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsVerSuccStartRepEnableCheck");
   return 1;
}

