/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(1,6) VerFailedPrgrRep as an out-going report.
 *
 * @note This file was generated on 2018-10-28 20:42:51
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsOutCmpVerFailedPrgrRep.h"

/**
 * Enable check of TM(1,6) VerFailedPrgrRep.
 * #TM(1,6)
 * @param smDesc The state machine descriptor.
 * @return The enable check result.
 */
CrFwBool_t CrPsOutCmpVerFailedPrgrRepEnableCheck(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsOutCmpVerFailedPrgrRepEnableCheck");
   return 1;
}

