/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(11,27) ScdGrpRep as an out-going report.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSOUTCMPSCDGRPREP_H_
#define CRPSOUTCMPSCDGRPREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Update action of TM(11,27) ScdGrpRep.
 * Collect the information about the currently used scheduling groups
 * @param smDesc The state machine descriptor.
 */
void CrPsOutCmpScdGrpRepUpdateAction(FwSmDesc_t smDesc);

/*----------------------------------------------------------------------------*/
#endif /* CRPSOUTCMPSCDGRPREP_H */
