/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(11,25) ScdDisGrpCmd.
 *
 * @note This file was generated on 2018-07-10 22:34:00
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSSCDDISGRPCMD_H_
#define CRPSSCDDISGRPCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(11,25) ScdDisGrpCmd.
 * Run the procedure Start Action of (11,24) and (11,25) Command of figure
 * \image html CrPsCmd11s24And25Start.png "Start Action of
 * Command to Enable or Disable Scheduling Groups". This procedure iterates
 * over the list of group identifiers in the command and rejects those which
 * are not in use.
 * @param smDesc The state machine descriptor.
 */
void CrPsScdDisGrpCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(11,25) ScdDisGrpCmd.
 * For all group identifiers accepted by the Start Action, the following is
 * done: the isGroupEnabled flag of the group is set to 'Disabled'. After all
 * identifiers have been processed, the action outcome is set to 'completed'.
 * @param smDesc The state machine descriptor.
 */
void CrPsScdDisGrpCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSSCDDISGRPCMD_H */
