/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(11,1) ScdEnbTbsCmd.
 *
 * @note This file was generated on 2018-07-10 22:34:00
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsScdEnbTbsCmd.h"

/**
 * Progress action of TC(11,1) ScdEnbTbsCmd.
 * Set the enable status of the time-based schedule execution function to:
 * enabled and start the Time-Based Schedule Execution Procedure of figure
 * \image html CrPsTbsExec "Time-Based Schedule Execution Procedure"
 * @param smDesc The state machine descriptor.
 */
void CrPsScdEnbTbsCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsScdEnbTbsCmdProgressAction");
   return 1;
}

