/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(11,2) ScdDisTbsCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-30 23:01:15
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSINCMDSCDDISTBSCMD_H_
#define CRPSINCMDSCDDISTBSCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Progress action of TC(11,2) ScdDisTbsCmd.
 * Set the enable status of the time-based schedule execution function to:
 * disabled and stop the Time-Based Schedule Execution Procedure of figure
 * \image html CrPsTbsExec "Time-Based Schedule Execution Procedure"
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdScdDisTbsCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSINCMDSCDDISTBSCMD_H */
