/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(11,2) ScdDisTbsCmd as an incoming command.
 *
 * @note This file was generated on 2018-08-19 17:56:57
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsInCmdScdDisTbsCmd.h"

/**
 * Progress action of TC(11,2) ScdDisTbsCmd.
 * Set the enable status of the time-based schedule execution function to:
 * disabled and stop the Time-Based Schedule Execution Procedure of figure
 * \image html CrPsTbsExec "Time-Based Schedule Execution Procedure"
 * @param smDesc The state machine descriptor.
 */
void CrPsScdDisTbsCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsScdDisTbsCmdProgressAction");
   return ;
}

