/**
 * @file
 * @ingroup gen_cfw
 *
 * This file is part of the PUS Extension of the CORDET Framework.
 *
 * @note This file was generated on 2018-07-14 16:54:25
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRFWINFACTORYUSERPAR_H_
#define CRFWINFACTORYUSERPAR_H_

#include "Hk/CrPsHkCreHkCmd.h"
#include "Hk/CrPsHkCreDiagCmd.h"
#include "Hk/CrPsHkDelHkCmd.h"
#include "Hk/CrPsHkDelDiagCmd.h"
#include "Hk/CrPsHkEnbHkCmd.h"
#include "Hk/CrPsHkDisHkCmd.h"
#include "Hk/CrPsHkEnbDiagCmd.h"
#include "Hk/CrPsHkDisDiagCmd.h"
#include "Hk/CrPsHkRepStructHkCmd.h"
#include "Hk/CrPsHkRepStructDiagCmd.h"
#include "Hk/CrPsHkOneShotHkCmd.h"
#include "Hk/CrPsHkOneShotDiagCmd.h"
#include "Evt/CrPsEvtEnbId.h"
#include "Evt/CrPsEvtDisIdCmd.h"
#include "Evt/CrPsEvtRepDisIdCmd.h"
#include "Scd/CrPsScdEnbTbsCmd.h"
#include "Scd/CrPsScdDisTbsCmd.h"
#include "Scd/CrPsScdResTbsCmd.h"
#include "Scd/CrPsScdInsTbaCmd.h"
#include "Scd/CrPsScdDelTbaCmd.h"
#include "Scd/CrPsScdEnbSubSchedCmd.h"
#include "Scd/CrPsScdDisSubSchedCmd.h"
#include "Scd/CrPsScdCreGrpCmd.h"
#include "Scd/CrPsScdDelGrpCmd.h"
#include "Scd/CrPsScdEnbGrpCmd.h"
#include "Scd/CrPsScdDisGrpCmd.h"
#include "Scd/CrPsScdRepGrpCmd.h"
#include "Mon/CrPsMonEnbParMonDefCmd.h"
#include "Mon/CrPsMonDisParMonDefCmd.h"
#include "Mon/CrPsMonChgTransDelCmd.h"
#include "Mon/CrPsMonDelAllParMonCmd.h"
#include "Mon/CrPsMonAddParMonDefCmd.h"
#include "Mon/CrPsMonDelParMonDefCmd.h"
#include "Mon/CrPsMonModParMonDefCmd.h"
#include "Mon/CrPsMonRepParMonDefCmd.h"
#include "Mon/CrPsMonRepOutOfLimitsCmd.h"
#include "Mon/CrPsMonRepParMonStatCmd.h"
#include "Mon/CrPsMonEnbParMonFuncCmd.h"
#include "Mon/CrPsMonDisParMonFuncCmd.h"
#include "Mon/CrPsMonEnbFuncMonCmd.h"
#include "Mon/CrPsMonDisFuncMonCmd.h"
#include "Mon/CrPsMonEnbFuncMonDefCmd.h"
#include "Mon/CrPsMonDisFuncMonDefCmd.h"
#include "Mon/CrPsMonProtFuncMonDefCmd.h"
#include "Mon/CrPsMonUnprotFuncMonDefCmd.h"
#include "Mon/CrPsMonAddFuncMonDefCmd.h"
#include "Mon/CrPsMonDelFuncMonDefCmd.h"
#include "Mon/CrPsMonRepFuncMonDefCmd.h"
#include "Mon/CrPsMonRepFuncMonStatCmd.h"
#include "Lpt/CrPsLptUpFirstCmd.h"
#include "Lpt/CrPsLptUpInterCmd.h"
#include "Lpt/CrPsLptUpLastCmd.h"
#include "Lpt/CrPsLptStartDownCmd.h"
#include "Lpt/CrPsLptAbortDownCmd.h"
#include "Tst/CrPsTstAreYouAliveCmd.h"
#include "Tst/CrPsTstConnectCmd.h"


/**
 * The maximum number of InCommands which may be allocated at any one time.
 */
#define CR_FW_INFACTORY_MAX_NOF_INCMD (63)

/**
 * The maximum number of InReports which may be allocated at any one time.
 */
#define CR_FW_INFACTORY_MAX_NOF_INREP (63)

/**
 * The total number of kinds of incoming commands supported by the
 * application.
 */
#define CR_FW_INCMD_NKINDS (56)

/**
 * The total number of kinds of incoming reports supported by the application.
 */
#define CR_FW_INREP_NKINDS (0)

/**
 * Definition of the incoming command kinds supported by an application.
 */
#define CR_FW_INCMD_INIT_KIND_DESC {\
   {3, 1, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkCreHkCmdStartAction, \
      &CrPsHkCreHkCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {3, 2, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkCreDiagCmdStartAction, \
      &CrPsHkCreDiagCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {3, 3, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkDelHkCmdStartAction, \
      &CrPsHkDelHkCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {3, 4, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkDelDiagCmdStartAction, \
      &CrPsHkDelDiagCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {3, 5, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkEnbHkCmdStartAction, \
      &CrPsHkEnbHkCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {3, 6, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkDisHkCmdStartAction, \
      &CrPsHkDisHkCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {3, 7, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkEnbDiagCmdStartAction, \
      &CrPsHkEnbDiagCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {3, 8, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkDisDiagCmdStartAction, \
      &CrPsHkDisDiagCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {3, 9, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkRepStructHkCmdStartAction, \
      &CrPsHkRepStructHkCmdProgressAction, &CrPsHkRepStructHkCmdTerminationAction, &CrFwSmEmptyAction}, \
   {3, 11, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsHkRepStructDiagCmdStartAction, \
      &CrPsHkRepStructDiagCmdProgressAction, &CrPsHkRepStructDiagCmdTerminationAction, &CrFwSmEmptyAction}, \
   {3, 27, 0, &CrPsHkOneShotHkCmdAcceptanceCheck, &CrPsHkOneShotHkCmdReadyCheck, &CrPsHkOneShotHkCmdStartAction, \
      &CrPsHkOneShotHkCmdProgressAction, &CrPsHkOneShotHkCmdTerminationAction, &CrPsHkOneShotHkCmdAbortAction}, \
   {3, 28, 0, &CrPsHkOneShotDiagCmdAcceptanceCheck, &CrPsHkOneShotDiagCmdReadyCheck, &CrPsHkOneShotDiagCmdStartAction, \
      &CrPsHkOneShotDiagCmdProgressAction, &CrPsHkOneShotDiagCmdTerminationAction, &CrPsHkOneShotDiagCmdAbortAction}, \
   {5, 5, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsEvtEnbIdStartAction, \
      &CrPsEvtEnbIdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {5, 6, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsEvtDisIdCmdStartAction, \
      &CrPsEvtDisIdCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {5, 7, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsEvtRepDisIdCmdStartAction, \
      &CrPsEvtRepDisIdCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 1, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrFwSmEmptyAction, \
      &CrPsScdEnbTbsCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 2, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrFwSmEmptyAction, \
      &CrPsScdDisTbsCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 3, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrFwSmEmptyAction, \
      &CrPsScdResTbsCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 4, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdInsTbaCmdStartAction, \
      &CrPsScdInsTbaCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 5, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdDelTbaCmdStartAction, \
      &CrPsScdDelTbaCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 20, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdEnbSubSchedCmdStartAction, \
      &CrPsScdEnbSubSchedCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 21, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdDisSubSchedCmdStartAction, \
      &CrPsScdDisSubSchedCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 22, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdCreGrpCmdStartAction, \
      &CrPsScdCreGrpCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 23, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdDelGrpCmdStartAction, \
      &CrPsScdDelGrpCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 24, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdEnbGrpCmdStartAction, \
      &CrPsScdEnbGrpCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 25, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdDisGrpCmdStartAction, \
      &CrPsScdDisGrpCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {11, 26, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsScdRepGrpCmdStartAction, \
      &CrPsScdRepGrpCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 1, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonEnbParMonDefCmdStartAction, \
      &CrPsMonEnbParMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 2, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonDisParMonDefCmdStartAction, \
      &CrPsMonDisParMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 3, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonChgTransDelCmdStartAction, \
      &CrPsMonChgTransDelCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 4, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonDelAllParMonCmdStartAction, \
      &CrPsMonDelAllParMonCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 5, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonAddParMonDefCmdStartAction, \
      &CrPsMonAddParMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 6, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonDelParMonDefCmdStartAction, \
      &CrPsMonDelParMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 7, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonModParMonDefCmdStartAction, \
      &CrPsMonModParMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 8, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonRepParMonDefCmdStartAction, \
      &CrPsMonRepParMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 10, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonRepOutOfLimitsCmdStartAction, \
      &CrPsMonRepOutOfLimitsCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 13, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonRepParMonStatCmdStartAction, \
      &CrPsMonRepParMonStatCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 15, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonEnbParMonFuncCmdStartAction, \
      &CrPsMonEnbParMonFuncCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 16, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonDisParMonFuncCmdStartAction, \
      &CrPsMonDisParMonFuncCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 17, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonEnbFuncMonCmdStartAction, \
      &CrPsMonEnbFuncMonCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 18, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrFwSmEmptyAction, \
      &CrPsMonDisFuncMonCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 19, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonEnbFuncMonDefCmdStartAction, \
      &CrPsMonEnbFuncMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 20, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonDisFuncMonDefCmdStartAction, \
      &CrPsMonDisFuncMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 21, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonProtFuncMonDefCmdStartAction, \
      &CrPsMonProtFuncMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 22, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonUnprotFuncMonDefCmdStartAction, \
      &CrPsMonUnprotFuncMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 23, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonAddFuncMonDefCmdStartAction, \
      &CrPsMonAddFuncMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 24, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonDelFuncMonDefCmdStartAction, \
      &CrPsMonDelFuncMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 25, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonRepFuncMonDefCmdStartAction, \
      &CrPsMonRepFuncMonDefCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {12, 27, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsMonRepFuncMonStatCmdStartAction, \
      &CrPsMonRepFuncMonStatCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {13, 9, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsLptUpFirstCmdStartAction, \
      &CrPsLptUpFirstCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {13, 10, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsLptUpInterCmdStartAction, \
      &CrPsLptUpInterCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {13, 11, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsLptUpLastCmdStartAction, \
      &CrPsLptUpLastCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {13, 129, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsLptStartDownCmdStartAction, \
      &CrPsLptStartDownCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {13, 130, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsLptAbortDownCmdStartAction, \
      &CrPsLptAbortDownCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {17, 1, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsTstAreYouAliveCmdStartAction, \
      &CrPsTstAreYouAliveCmdProgressAction, &CrFwSmEmptyAction, &CrFwSmEmptyAction}, \
   {17, 3, 0, &CrFwPrCheckAlwaysTrue, &CrFwSmCheckAlwaysTrue, &CrPsTstConnectCmdStartAction, \
      &CrPsTstConnectCmdProgressAction, &CrPsTstConnectCmdTerminationAction, &CrFwSmEmptyAction} \
}

/**
 * Definition of the incoming report kinds supported by an application.
 */
#define CR_FW_INREP_INIT_KIND_DESC {\
}

/*----------------------------------------------------------------------------*/
#endif /* CRFWINFACTORYUSERPAR_H */
