/**
 * @file
 * @ingroup gen_pck
 *
 * Type definitions.
 *
 * @note This file was generated on 2018-10-28 17:05:47
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSTYPES_H_
#define CRPSTYPES_H_

#include "CrFwUserConstants.h"
#include "CrFwConstants.h"

/**
 * Definition of type "CrPsFailData_t".
 */
typedef unsigned int CrPsFailData_t;

/**
 * Definition of type "CrPsOneBit_t".
 */
typedef unsigned char CrPsOneBit_t;

/**
 * Definition of type "CrPsTwoBit_t".
 */
typedef unsigned char CrPsTwoBit_t;

/**
 * Definition of type "CrPsThreeBit_t".
 */
typedef unsigned char CrPsThreeBit_t;

/**
 * Definition of type "CrPsFourBit_t".
 */
typedef unsigned char CrPsFourBit_t;

/**
 * Definition of type "CrPsFourteenBit_t".
 */
typedef unsigned short CrPsFourteenBit_t;

/**
 * Definition of type "CrPsElevenBit_t".
 */
typedef unsigned short CrPsElevenBit_t;

/**
 * Definition of type "CrPsCollectInterval_t".
 */
typedef unsigned short CrPsCollectInterval_t;

/**
 * Definition of type "CrPsPartSeqNmb_t".
 */
typedef unsigned short CrPsPartSeqNmb_t;

/**
 * Definition of type "CrPsTransId_t".
 */
typedef unsigned short CrPsTransId_t;

/**
 * Definition of type "CrPsSID_t".
 */
typedef unsigned short CrPsSID_t;

/**
 * Definition of type "CrPsRepNum_t".
 */
typedef unsigned char CrPsRepNum_t;

/**
 * Definition of type "CrPsFailReason_t".
 */
typedef unsigned short CrPsFailReason_t;

/**
 * Definition of type "CrPsNParMon_t".
 */
typedef unsigned char CrPsNParMon_t;

/**
 * Definition of type "CrPsNFuncMon_t".
 */
typedef unsigned char CrPsNFuncMon_t;

/**
 * Definition of type "CrPsFunctMonCheckStatus_t".
 */
typedef unsigned char CrPsFunctMonCheckStatus_t;
enum {
   MON_UNCHECKED = 1,
   MON_INVALID = 2,
   MON_RUNNING = 3,
   MON_FAILED = 4
};

/**
 * Definition of type "CrPsParMonCheckStatus_t".
 */
typedef unsigned char CrPsParMonCheckStatus_t;
enum {
   MON_VALID = 1,
   MON_NOT_EXP = 2,
   MON_ABOVE = 3,
   MON_BELOW = 4,
   MON_DEL_ABOVE = 5,
   MON_DEL_BELOW = 6
};

/**
 * Definition of type "CrPsMonCheckType_t".
 */
typedef unsigned char CrPsMonCheckType_t;
enum {
   EXP_VAL_CHECK = 1,
   LIM_CHECK = 2,
   DEL_CHECK = 3
};

/**
 * Definition of type "CrPsEvtId_t".
 */
typedef unsigned short CrPsEvtId_t;
enum {
   EVT_DOWN_ABORT = 1,
   EVT_UP_ABORT = 2,
   EVT_MON_LIM_R = 3,
   EVT_MON_LIM_I = 4,
   EVT_MON_EXP = 5,
   EVT_MON_DEL_R = 6,
   EVT_MON_DEL_I = 7,
   EVT_FMON_FAIL = 8,
   EVT_CLST_FULL = 9,
   EVT_DUMMY = 255
};

/**
 * Definition of type "CrPsValCheckExpVal_t".
 */
typedef unsigned short CrPsValCheckExpVal_t;

/**
 * Definition of type "CrPsRepNumber_t".
 */
typedef unsigned char CrPsRepNumber_t;

/**
 * Definition of type "CrPsMinFailNmb_t".
 */
typedef unsigned char CrPsMinFailNmb_t;

/**
 * Definition of type "CrPsParMonId_t".
 */
typedef unsigned short CrPsParMonId_t;

/**
 * Definition of type "CrPsFuncMonId_t".
 */
typedef unsigned char CrPsFuncMonId_t;

/**
 * Definition of type "CrPsProtStatus_t".
 */
typedef unsigned char CrPsProtStatus_t;
enum {
   UNPROTECTED = 0,
   PROTECTED = 1
};

/**
 * Definition of type "CrPsRepDelay_t".
 */
typedef unsigned short CrPsRepDelay_t;

/**
 * Definition of type "CrPsAckFlag_t".
 */
typedef unsigned char CrPsAckFlag_t;
enum {
   NO_ACK = 0,
   ACK = 1
};

/**
 * Definition of type "CrPsThirteenBit_t".
 */
typedef unsigned short CrPsThirteenBit_t;

/**
 * Definition of type "CrPsSixteenBit_t".
 */
typedef unsigned short CrPsSixteenBit_t;

/**
 * Definition of type "CrPsThirtytwoBit_t".
 */
typedef unsigned int CrPsThirtytwoBit_t;

/**
 * Definition of type "CrPsPrgStep_t".
 */
typedef unsigned char CrPsPrgStep_t;

/**
 * Definition of type "CrPsNPar_t".
 */
typedef unsigned char CrPsNPar_t;

/**
 * Definition of type "CrPsParId_t".
 */
typedef unsigned short CrPsParId_t;

/**
 * Definition of type "CrPsNGroups_t".
 */
typedef unsigned char CrPsNGroups_t;

/**
 * Definition of type "CrPsNSID_t".
 */
typedef unsigned char CrPsNSID_t;

/**
 * Definition of type "CrPsEnDis_t".
 */
typedef unsigned char CrPsEnDis_t;
enum {
   DISABLED = 0,
   ENABLED = 1
};

/**
 * Definition of type "CrPsNEvtId_t".
 */
typedef unsigned char CrPsNEvtId_t;

/**
 * Definition of type "CrPsEightBit_t".
 */
typedef unsigned char CrPsEightBit_t;

/**
 * Definition of type "CrPsNEvtRep_t".
 */
typedef unsigned short CrPsNEvtRep_t;

/**
 * Definition of type "CrPsCycleCnt_t".
 */
typedef unsigned short CrPsCycleCnt_t;

/**
 * Definition of type "CrPsSampleBufId_t".
 */
typedef unsigned char CrPsSampleBufId_t;

/**
 * Definition of type "CrPsTimeSec_t".
 */
typedef unsigned int CrPsTimeSec_t;

/**
 * Definition of type "CrPsNOfCmd_t".
 */
typedef unsigned short CrPsNOfCmd_t;

/**
 * Definition of type "CrPsNOfLinks_t".
 */
typedef unsigned char CrPsNOfLinks_t;

/**
 * Definition of type "CrPsSize_t".
 */
typedef unsigned short CrPsSize_t;

/**
 * Definition of type "CrPsNCmdRep_t".
 */
typedef unsigned int CrPsNCmdRep_t;

/**
 * Definition of type "CrPsNTba_t".
 */
typedef unsigned short CrPsNTba_t;

/**
 * Definition of type "CrPsNSubSchedGroup_t".
 */
typedef unsigned char CrPsNSubSchedGroup_t;

/**
 * Definition of type "CrPsErrRepCode_t".
 */
typedef unsigned char CrPsErrRepCode_t;
enum {
   INLOADER_ACC_FAIL = 200,
   INLOADER_INV_DEST = 201,
   OUTFACTORY_FAIL = 202,
   SNDPCKT_INV_DEST = 203
};

/**
 * Definition of type "CrPsFailCode_t".
 */
typedef CrFwOutcome_t CrPsFailCode_t;
enum {
   VER_CMD_INV_DEST = 129,
   VER_REP_CR_FD = 130,
   VER_OUTLOADER_FD = 131,
   VER_SID_IN_USE = 132,
   VER_FULL_RDL = 133,
   VER_RDL_CONSTR = 134,
   VER_DUPL_DI = 135,
   VER_ILL_SID = 136,
   VER_ENABLED_SID = 137,
   VER_SID_START_FD = 138,
   VER_FACT_PRGR_FD = 139,
   VER_ILL_EID = 140,
   VER_EID_ST_FD = 141,
   VER_ILL_MON = 142,
   VER_MON_START_FD = 143,
   VER_PMDL_FULL = 144,
   VER_MON_ILL_DI = 145,
   VER_MON_PROT = 146,
   VER_MON_ENB = 147,
   VER_MON_USE = 148,
   VER_FMDL_FULL = 149,
   VER_MON_TMP = 150,
   VER_MON_MFN = 152,
   VER_SCD_ILL_SS = 153,
   VER_FULL_TBS = 154,
   VER_SCD_ILL_G = 155,
   VER_SCD_ILL_RT = 156,
   VER_SCD_ILL_DS = 157,
   VER_SCD_CRFAIL = 158,
   VER_SCD_ST_FD = 159,
   VER_ILL_ACT_ID = 160,
   VER_TST_TO = 161,
   VER_CRE_FD = 254,
   VER_CMD_LD_FD = 255
};


/*----------------------------------------------------------------------------*/
#endif /* CRPSTYPES_H */
