/**
 * \file
 *
 * Interface for accessing data pool items.
 *
 * \note This file was generated on 2018-06-22 17:45:58
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software GmbH
 */
#ifndef CRPSDPSCD_H_
#define CRPSDPSCD_H_

#include "CrPsDpTypes.h"
#include "CrPsConstants.h"

/**
 * Type description
 */
typedef struct {
   /**
    * Enable status of a sub-schedule
    */
   CrFwBool_t isSubSchedEnabled[SCD_N_SUB_TBS];
   /**
    * Enable status of time-based schedule
    */
   CrFwBool_t isTbsEnabled;
   /**
    * Number of TBAs in group
    */
   CrPsNTba_t nOfTbaInGroup[SCD_N_GROUP];
   /**
    * Number of TBAs in sub-schedule
    */
   CrPsNTba_t nOfTbaInSubSched[SCD_N_SUB_TBS];
   /**
    * Time margin for time-based scheduling service
    */
   CrFwTimeStamp_t timeMargin;
} DpScdParams_t;

/**
 * Type description
 */
typedef struct {
   /**
    * Identifier of next time-based activity due for release
    */
   CrPsNTba_t firstTba;
   /**
    * Enabled flag for time-based schedule group
    */
   CrFwBool_t isGroupEnabled[SCD_N_GROUP];
   /**
    * InUse flag for time-based schedule group
    */
   CrFwBool_t isGroupInUse[SCD_N_GROUP];
   /**
    * Number of non-empty groups
    */
   CrPsNSubSchedGroup_t nOfGroup;
   /**
    * Number of non-empty sub-schedules
    */
   CrPsNSubSchedGroup_t nOfSubSched;
   /**
    * Number of currently defined time-based activities (TBAs)
    */
   CrPsNTba_t nOfTba;
} DpScdVars_t;

extern DpScdParams_t dpScdParams;
extern DpScdVars_t dpScdVars;

/**
 * Initialises Scd
 */
void initDpScd(void);

/**
 * Gets the datapool array isSubSchedEnabled
 * \return The datapool array isSubSchedEnabled
 */
static inline CrFwBool_t* getDpisSubSchedEnabledArray()
{
   return &dpScdParams.isSubSchedEnabled[0];
}

/**
 * Gets the value of the i-th element in the datapool array isSubSchedEnabled
 * \param i Index variable
 * \return The i-th element in the datapool array isSubSchedEnabled
 */
static inline CrFwBool_t getDpisSubSchedEnabledItem(int i)
{
   return dpScdParams.isSubSchedEnabled[i];
}

/**
 * Sets the value of the i-th element in the datapool array isSubSchedEnabled
 * \param i Index variable
 * \param isSubSchedEnabled The value to be stored into the i-th element of
 * datapool array isSubSchedEnabled.
 */
static inline void setDpisSubSchedEnabledItem(int i, CrFwBool_t isSubSchedEnabled)
{
   dpScdParams.isSubSchedEnabled[i] = isSubSchedEnabled;
}

/**
 * Gets the value of the datapool item isTbsEnabled
 * \return The value of datapool item isTbsEnabled
 */
static inline CrFwBool_t getDpisTbsEnabled()
{
   return dpScdParams.isTbsEnabled;
}

/**
 * Sets the value of the datapool item isTbsEnabled
 * \param isTbsEnabled The value to be stored into the datapool item
 * isTbsEnabled.
 */
static inline void setDpisTbsEnabled(CrFwBool_t isTbsEnabled)
{
   dpScdParams.isTbsEnabled = isTbsEnabled;
}

/**
 * Gets the datapool array nOfTbaInGroup
 * \return The datapool array nOfTbaInGroup
 */
static inline CrPsNTba_t* getDpnOfTbaInGroupArray()
{
   return &dpScdParams.nOfTbaInGroup[0];
}

/**
 * Gets the value of the i-th element in the datapool array nOfTbaInGroup
 * \param i Index variable
 * \return The i-th element in the datapool array nOfTbaInGroup
 */
static inline CrPsNTba_t getDpnOfTbaInGroupItem(int i)
{
   return dpScdParams.nOfTbaInGroup[i];
}

/**
 * Sets the value of the i-th element in the datapool array nOfTbaInGroup
 * \param i Index variable
 * \param nOfTbaInGroup The value to be stored into the i-th element of
 * datapool array nOfTbaInGroup.
 */
static inline void setDpnOfTbaInGroupItem(int i, CrPsNTba_t nOfTbaInGroup)
{
   dpScdParams.nOfTbaInGroup[i] = nOfTbaInGroup;
}

/**
 * Gets the datapool array nOfTbaInSubSched
 * \return The datapool array nOfTbaInSubSched
 */
static inline CrPsNTba_t* getDpnOfTbaInSubSchedArray()
{
   return &dpScdParams.nOfTbaInSubSched[0];
}

/**
 * Gets the value of the i-th element in the datapool array nOfTbaInSubSched
 * \param i Index variable
 * \return The i-th element in the datapool array nOfTbaInSubSched
 */
static inline CrPsNTba_t getDpnOfTbaInSubSchedItem(int i)
{
   return dpScdParams.nOfTbaInSubSched[i];
}

/**
 * Sets the value of the i-th element in the datapool array nOfTbaInSubSched
 * \param i Index variable
 * \param nOfTbaInSubSched The value to be stored into the i-th element of
 * datapool array nOfTbaInSubSched.
 */
static inline void setDpnOfTbaInSubSchedItem(int i, CrPsNTba_t nOfTbaInSubSched)
{
   dpScdParams.nOfTbaInSubSched[i] = nOfTbaInSubSched;
}

/**
 * Gets the value of the datapool item timeMargin
 * \return The value of datapool item timeMargin
 */
static inline CrFwTimeStamp_t getDptimeMargin()
{
   return dpScdParams.timeMargin;
}

/**
 * Sets the value of the datapool item timeMargin
 * \param timeMargin The value to be stored into the datapool item timeMargin.
 */
static inline void setDptimeMargin(CrFwTimeStamp_t timeMargin)
{
   dpScdParams.timeMargin = timeMargin;
}

/**
 * Gets the value of the datapool item firstTba
 * \return The value of datapool item firstTba
 */
static inline CrPsNTba_t getDpfirstTba()
{
   return dpScdVars.firstTba;
}

/**
 * Sets the value of the datapool item firstTba
 * \param firstTba The value to be stored into the datapool item firstTba.
 */
static inline void setDpfirstTba(CrPsNTba_t firstTba)
{
   dpScdVars.firstTba = firstTba;
}

/**
 * Gets the datapool array isGroupEnabled
 * \return The datapool array isGroupEnabled
 */
static inline CrFwBool_t* getDpisGroupEnabledArray()
{
   return &dpScdVars.isGroupEnabled[0];
}

/**
 * Gets the value of the i-th element in the datapool array isGroupEnabled
 * \param i Index variable
 * \return The i-th element in the datapool array isGroupEnabled
 */
static inline CrFwBool_t getDpisGroupEnabledItem(int i)
{
   return dpScdVars.isGroupEnabled[i];
}

/**
 * Sets the value of the i-th element in the datapool array isGroupEnabled
 * \param i Index variable
 * \param isGroupEnabled The value to be stored into the i-th element of
 * datapool array isGroupEnabled.
 */
static inline void setDpisGroupEnabledItem(int i, CrFwBool_t isGroupEnabled)
{
   dpScdVars.isGroupEnabled[i] = isGroupEnabled;
}

/**
 * Gets the datapool array isGroupInUse
 * \return The datapool array isGroupInUse
 */
static inline CrFwBool_t* getDpisGroupInUseArray()
{
   return &dpScdVars.isGroupInUse[0];
}

/**
 * Gets the value of the i-th element in the datapool array isGroupInUse
 * \param i Index variable
 * \return The i-th element in the datapool array isGroupInUse
 */
static inline CrFwBool_t getDpisGroupInUseItem(int i)
{
   return dpScdVars.isGroupInUse[i];
}

/**
 * Sets the value of the i-th element in the datapool array isGroupInUse
 * \param i Index variable
 * \param isGroupInUse The value to be stored into the i-th element of
 * datapool array isGroupInUse.
 */
static inline void setDpisGroupInUseItem(int i, CrFwBool_t isGroupInUse)
{
   dpScdVars.isGroupInUse[i] = isGroupInUse;
}

/**
 * Gets the value of the datapool item nOfGroup
 * \return The value of datapool item nOfGroup
 */
static inline CrPsNSubSchedGroup_t getDpnOfGroup()
{
   return dpScdVars.nOfGroup;
}

/**
 * Sets the value of the datapool item nOfGroup
 * \param nOfGroup The value to be stored into the datapool item nOfGroup.
 */
static inline void setDpnOfGroup(CrPsNSubSchedGroup_t nOfGroup)
{
   dpScdVars.nOfGroup = nOfGroup;
}

/**
 * Gets the value of the datapool item nOfSubSched
 * \return The value of datapool item nOfSubSched
 */
static inline CrPsNSubSchedGroup_t getDpnOfSubSched()
{
   return dpScdVars.nOfSubSched;
}

/**
 * Sets the value of the datapool item nOfSubSched
 * \param nOfSubSched The value to be stored into the datapool item
 * nOfSubSched.
 */
static inline void setDpnOfSubSched(CrPsNSubSchedGroup_t nOfSubSched)
{
   dpScdVars.nOfSubSched = nOfSubSched;
}

/**
 * Gets the value of the datapool item nOfTba
 * \return The value of datapool item nOfTba
 */
static inline CrPsNTba_t getDpnOfTba()
{
   return dpScdVars.nOfTba;
}

/**
 * Sets the value of the datapool item nOfTba
 * \param nOfTba The value to be stored into the datapool item nOfTba.
 */
static inline void setDpnOfTba(CrPsNTba_t nOfTba)
{
   dpScdVars.nOfTba = nOfTba;
}


/*----------------------------------------------------------------------------*/
#endif /* CRPSDPSCD_H */
