/**
 * @file
 * @ingroup gen_dp
 *
 * Interface for accessing data pool items.
 *
 * @note This file was generated on 2018-07-14 22:58:14
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsDpVer.h"


DpVerVars_t dpVerVars  = { \
   0, /* failCodeAccFailed */ \
   0, /* failCodePrgrFailed */ \
   0, /* failCodeStartFailed */ \
   0, /* failCodeTermFailed */ \
   0, /* invDestRerouting */ \
   0, /* nOfAccFailed */ \
   0, /* nOfPrgrFailed */ \
   0, /* nOfReroutingFailed */ \
   0, /* nOfStartFailed */ \
   0, /* nOfTermFailed */ \
   0, /* pcktIdAccFailed */ \
   0, /* pcktIdPrgrFailed */ \
   0, /* pcktIdReroutingFailed */ \
   0, /* pcktIdStartFailed */ \
   0, /* pcktIdTermFailed */ \
   0, /* stepPrgrFailed */ \
   0, /* verFailCode */ \
   0 /* verFailData */ \
};

