/**
 * @file
 * @ingroup gen_dp
 *
 * Interface for accessing data pool items.
 *
 * @note This file was generated on 2018-10-28 20:42:50
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsDpLpt.h"

DpLptParams_t dpLptParams  = { \
   {0}, /* lptDest */ \
   {0}, /* lptTimeOut */ \
   {0} /* partSize */ \
};

DpLptVars_t dpLptVars  = { \
   {0}, /* lptRemSize */ \
   {0}, /* lptSize */ \
   {0}, /* lptSrc */ \
   {0}, /* lptTime */ \
   0, /* nOfDownlinks */ \
   0, /* nOfUplinks */ \
   {0} /* partSeqNmb */ \
};

