/**
 * @file
 * @ingroup gen_dp
 *
 * Interface for accessing data pool items.
 *
 * @note This file was generated on 2018-07-14 22:58:14
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsDpMon.h"

DpMonParams_t dpMonParams  = { \
   0, /* maxRepDelay */ \
   0 /* servUser */ \
};

DpMonVars_t dpMonVars  = { \
   0, /* ctlRepDelay */ \
   0, /* ctlTimeFirstEntry */ \
   0, /* funcMonEnbStatus */ \
   0, /* nmbAvailFuncMon */ \
   0, /* nmbAvailParMon */ \
   0, /* nmbEnbFuncMon */ \
   0, /* nmbEnbParMon */ \
   ENABLED /* parMonEnbStatus */ \
};

