/**
 * \file
 *
 * Interface for accessing data pool items.
 *
 * \note This file was generated on 2018-05-19 23:24:03
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software GmbH
 */

#include "CrPsDpTst.h"

DpTstParams_t dpTstParams ;
DpTstVars_t dpTstVars ;

/**
 * Initialises Tst
 */
void initDpTst(void)
{
   static const DestSrc_t initOnBoardConnectDestLst[TST_N_DEST] = 0;

   dpTstParams.AreYouAliveTimeOut = 10;
   memcpy(dpTstParams.OnBoardConnectDestLst, initOnBoardConnectDestLst, sizeof(dpTstParams.OnBoardConnectDestLst));
   dpTstVars.AreYouAliveSrc = 0;
   dpTstVars.OnBoardConnectDest = 0;
}
