/**
 * \file
 *
 * Interface for accessing data pool items.
 *
 * \note This file was generated on 2018-06-22 17:45:58
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software GmbH
 */
#ifndef CRPSDPHK_H_
#define CRPSDPHK_H_

#include "CrPsDpTypes.h"
#include "CrPsConstants.h"

/**
 * Type description
 */
typedef struct {
   /**
    * Address of Debug Variables
    */
   CrPsThirtytwoBit_t debugVarAddr[HK_N_DEBUG_VAR];
   /**
    * Destination of report definitions in the RDL
    */
   CrFwDestSrc_t dest[HK_N_REP_DEF];
   /**
    * Enable status of report definitions in the RDL
    */
   CrFwBool_t isEnabled[HK_N_REP_DEF];
   /**
    * Periods of report definitions in the RDL
    */
   CrPsCycleCnt_t period[HK_N_REP_DEF];
   /**
    * SIDs of report definitions in the RDL
    */
   CrPsSID_t sid[HK_N_REP_DEF];
} DpHkParams_t;

/**
 * Type description
 */
typedef struct {
   /**
    * Cycle Counter for Reports in RDL
    */
   CrPsCycleCnt_t cycleCnt[HK_N_REP_DEF];
   /**
    * Value of Debug Variables
    */
   CrPsThirtytwoBit_t debugVar[HK_N_DEBUG_VAR];
   /**
    * The i-th element of this array is the identifier of the Sampling Buffer
    * for the i-th Report Definition in the RDL
    */
   CrPsSampleBufId_t sampleBufId[HK_N_REP_DEF];
} DpHkVars_t;

extern DpHkParams_t dpHkParams;
extern DpHkVars_t dpHkVars;

/**
 * Initialises Hk
 */
void initDpHk(void);

/**
 * Gets the datapool array debugVarAddr
 * \return The datapool array debugVarAddr
 */
static inline CrPsThirtytwoBit_t* getDpdebugVarAddrArray()
{
   return &dpHkParams.debugVarAddr[0];
}

/**
 * Gets the value of the i-th element in the datapool array debugVarAddr
 * \param i Index variable
 * \return The i-th element in the datapool array debugVarAddr
 */
static inline CrPsThirtytwoBit_t getDpdebugVarAddrItem(int i)
{
   return dpHkParams.debugVarAddr[i];
}

/**
 * Sets the value of the i-th element in the datapool array debugVarAddr
 * \param i Index variable
 * \param debugVarAddr The value to be stored into the i-th element of
 * datapool array debugVarAddr.
 */
static inline void setDpdebugVarAddrItem(int i, CrPsThirtytwoBit_t debugVarAddr)
{
   dpHkParams.debugVarAddr[i] = debugVarAddr;
}

/**
 * Gets the datapool array dest
 * \return The datapool array dest
 */
static inline CrFwDestSrc_t* getDpdestArray()
{
   return &dpHkParams.dest[0];
}

/**
 * Gets the value of the i-th element in the datapool array dest
 * \param i Index variable
 * \return The i-th element in the datapool array dest
 */
static inline CrFwDestSrc_t getDpdestItem(int i)
{
   return dpHkParams.dest[i];
}

/**
 * Sets the value of the i-th element in the datapool array dest
 * \param i Index variable
 * \param dest The value to be stored into the i-th element of datapool array
 * dest.
 */
static inline void setDpdestItem(int i, CrFwDestSrc_t dest)
{
   dpHkParams.dest[i] = dest;
}

/**
 * Gets the datapool array isEnabled
 * \return The datapool array isEnabled
 */
static inline CrFwBool_t* getDpisEnabledArray()
{
   return &dpHkParams.isEnabled[0];
}

/**
 * Gets the value of the i-th element in the datapool array isEnabled
 * \param i Index variable
 * \return The i-th element in the datapool array isEnabled
 */
static inline CrFwBool_t getDpisEnabledItem(int i)
{
   return dpHkParams.isEnabled[i];
}

/**
 * Sets the value of the i-th element in the datapool array isEnabled
 * \param i Index variable
 * \param isEnabled The value to be stored into the i-th element of datapool
 * array isEnabled.
 */
static inline void setDpisEnabledItem(int i, CrFwBool_t isEnabled)
{
   dpHkParams.isEnabled[i] = isEnabled;
}

/**
 * Gets the datapool array period
 * \return The datapool array period
 */
static inline CrPsCycleCnt_t* getDpperiodArray()
{
   return &dpHkParams.period[0];
}

/**
 * Gets the value of the i-th element in the datapool array period
 * \param i Index variable
 * \return The i-th element in the datapool array period
 */
static inline CrPsCycleCnt_t getDpperiodItem(int i)
{
   return dpHkParams.period[i];
}

/**
 * Sets the value of the i-th element in the datapool array period
 * \param i Index variable
 * \param period The value to be stored into the i-th element of datapool
 * array period.
 */
static inline void setDpperiodItem(int i, CrPsCycleCnt_t period)
{
   dpHkParams.period[i] = period;
}

/**
 * Gets the datapool array sid
 * \return The datapool array sid
 */
static inline CrPsSID_t* getDpsidArray()
{
   return &dpHkParams.sid[0];
}

/**
 * Gets the value of the i-th element in the datapool array sid
 * \param i Index variable
 * \return The i-th element in the datapool array sid
 */
static inline CrPsSID_t getDpsidItem(int i)
{
   return dpHkParams.sid[i];
}

/**
 * Sets the value of the i-th element in the datapool array sid
 * \param i Index variable
 * \param sid The value to be stored into the i-th element of datapool array
 * sid.
 */
static inline void setDpsidItem(int i, CrPsSID_t sid)
{
   dpHkParams.sid[i] = sid;
}

/**
 * Gets the datapool array cycleCnt
 * \return The datapool array cycleCnt
 */
static inline CrPsCycleCnt_t* getDpcycleCntArray()
{
   return &dpHkVars.cycleCnt[0];
}

/**
 * Gets the value of the i-th element in the datapool array cycleCnt
 * \param i Index variable
 * \return The i-th element in the datapool array cycleCnt
 */
static inline CrPsCycleCnt_t getDpcycleCntItem(int i)
{
   return dpHkVars.cycleCnt[i];
}

/**
 * Sets the value of the i-th element in the datapool array cycleCnt
 * \param i Index variable
 * \param cycleCnt The value to be stored into the i-th element of datapool
 * array cycleCnt.
 */
static inline void setDpcycleCntItem(int i, CrPsCycleCnt_t cycleCnt)
{
   dpHkVars.cycleCnt[i] = cycleCnt;
}

/**
 * Gets the datapool array debugVar
 * \return The datapool array debugVar
 */
static inline CrPsThirtytwoBit_t* getDpdebugVarArray()
{
   return &dpHkVars.debugVar[0];
}

/**
 * Gets the value of the i-th element in the datapool array debugVar
 * \param i Index variable
 * \return The i-th element in the datapool array debugVar
 */
static inline CrPsThirtytwoBit_t getDpdebugVarItem(int i)
{
   return dpHkVars.debugVar[i];
}

/**
 * Sets the value of the i-th element in the datapool array debugVar
 * \param i Index variable
 * \param debugVar The value to be stored into the i-th element of datapool
 * array debugVar.
 */
static inline void setDpdebugVarItem(int i, CrPsThirtytwoBit_t debugVar)
{
   dpHkVars.debugVar[i] = debugVar;
}

/**
 * Gets the datapool array sampleBufId
 * \return The datapool array sampleBufId
 */
static inline CrPsSampleBufId_t* getDpsampleBufIdArray()
{
   return &dpHkVars.sampleBufId[0];
}

/**
 * Gets the value of the i-th element in the datapool array sampleBufId
 * \param i Index variable
 * \return The i-th element in the datapool array sampleBufId
 */
static inline CrPsSampleBufId_t getDpsampleBufIdItem(int i)
{
   return dpHkVars.sampleBufId[i];
}

/**
 * Sets the value of the i-th element in the datapool array sampleBufId
 * \param i Index variable
 * \param sampleBufId The value to be stored into the i-th element of datapool
 * array sampleBufId.
 */
static inline void setDpsampleBufIdItem(int i, CrPsSampleBufId_t sampleBufId)
{
   dpHkVars.sampleBufId[i] = sampleBufId;
}


/*----------------------------------------------------------------------------*/
#endif /* CRPSDPHK_H */
