/**
 * @file
 * @ingroup gen_dp
 *
 * Interface for accessing data pool items.
 *
 * @note This file was generated on 2018-10-28 17:05:46
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsDpTst.h"

DpTstParams_t dpTstParams  = { \
   0, /* AreYouAliveTimeOut */ \
   {0} /* OnBoardConnectDestLst */ \
};

DpTstVars_t dpTstVars  = { \
   0, /* AreYouAliveSrc */ \
   0, /* AreYouAliveStart */ \
   0 /* OnBoardConnectDest */ \
};

