/**
 * @file
 * @ingroup gen_dp
 *
 * Interface for accessing data pool items.
 *
 * @note This file was generated on 2018-07-10 22:24:45
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsDpScd.h"

DpScdParams_t dpScdParams  = { \
   {0}, \  /* isSubSchedEnabled */
   0, \  /* isTbsEnabled */
   {0}, \  /* nOfTbaInGroup */
   {0}, \  /* nOfTbaInSubSched */
   0 \  /* timeMargin */
};

DpScdVars_t dpScdVars  = { \
   0, \  /* firstTba */
   {1}, \  /* isGroupEnabled */
   {0}, \  /* isGroupInUse */
   0, \  /* nOfGroup */
   0, \  /* nOfSubSched */
   0 \  /* nOfTba */
};

