/**
 * @file
 * @ingroup gen_pck
 *
 * Interface for accessing fields in packets of service "Dum".
 *
 * @note This file was generated on 2018-09-29 16:05:17
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSPCKTDUM_H_
#define CRPSPCKTDUM_H_

#include "CrPsTypes.h"

#include "CrPsPckt.h"
/**
 * Structure for Sample1
 */
typedef struct __attribute__((packed)) _Sample1_t {
   /**
    * Packet header.
    */
   TcHeader_t Header;

} Sample1_t ;


/*----------------------------------------------------------------------------*/
#endif /* CRPSPCKTDUM_H */
