/**
 * @file
 * @ingroup gen_pck
 *
 * Interface for accessing fields in packets of service "Tst".
 *
 * @note This file was generated on 2018-09-30 23:01:15
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSPCKTTST_H_
#define CRPSPCKTTST_H_

#include "CrPsTypes.h"

#include "CrPsPckt.h"
/**
 * Structure for AreYouAliveCmd
 */
typedef struct __attribute__((packed)) _AreYouAliveCmd_t {
   /**
    * Packet header.
    */
   TcHeader_t Header;

} AreYouAliveCmd_t ;

/**
 * Structure for AreYouAliveRep
 */
typedef struct __attribute__((packed)) _AreYouAliveRep_t {
   /**
    * Packet header.
    */
   TmHeader_t Header;

} AreYouAliveRep_t ;

/**
 * Structure for ConnectCmd
 */
typedef struct __attribute__((packed)) _ConnectCmd_t {
   /**
    * Packet header.
    */
   TcHeader_t Header;

   /**
    * Identifier of the application with which the connection test must be
    * done
    */
   CrFwDestSrc_t AppId;
   
} ConnectCmd_t ;

/**
 * Structure for ConnectRep
 */
typedef struct __attribute__((packed)) _ConnectRep_t {
   /**
    * Packet header.
    */
   TmHeader_t Header;

   /**
    * Identifier of application with which the connection test was done
    */
   CrFwDestSrc_t AppId;
   
} ConnectRep_t ;

/**
 * Get "AppId" from "ConnectCmd" packet.
 * @param p Pointer to the packet.
 * @return Value of "AppId".
 */
static inline CrFwDestSrc_t getTstConnectCmdAppId(void* p) {
   ConnectCmd_t* t;
   t = (ConnectCmd_t*)p;
   return t->AppId;
}

/**
 * Set "AppId" in "ConnectCmd" packet.
 * @param p Pointer to the packet.
 * @param AppId Value of "AppId" to be set in packet.
 */
static inline void setTstConnectCmdAppId(void* p, CrFwDestSrc_t AppId) {
   ConnectCmd_t* t;
   t = (ConnectCmd_t*)p;
   t->AppId = AppId;
}

/**
 * Get "AppId" from "ConnectRep" packet.
 * @param p Pointer to the packet.
 * @return Value of "AppId".
 */
static inline CrFwDestSrc_t getTstConnectRepAppId(void* p) {
   ConnectRep_t* t;
   t = (ConnectRep_t*)p;
   return t->AppId;
}

/**
 * Set "AppId" in "ConnectRep" packet.
 * @param p Pointer to the packet.
 * @param AppId Value of "AppId" to be set in packet.
 */
static inline void setTstConnectRepAppId(void* p, CrFwDestSrc_t AppId) {
   ConnectRep_t* t;
   t = (ConnectRep_t*)p;
   t->AppId = AppId;
}


/*----------------------------------------------------------------------------*/
#endif /* CRPSPCKTTST_H */
