/**
 * @file
 *
 * Implementation of TM(5,1) EvtRep1 as an out-going report.
 *
 * @note This file was generated on 2018-10-28 17:05:47
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

/* Cordet Framework includes */
#include "OutRegistry/CrFwOutRegistry.h"
#include "OutCmp/CrFwOutCmp.h"

/* PUS Extension includes */
#include "CrPsOutCmpEvtRep1.h"
#include "DataPool/CrPsDpEvt.h"
#include "Pckt/CrPsPckt.h"
#include "Pckt/CrPsPcktEvt.h"
#include "CrPsConstants.h"

/**
 * Enable check of TM(5,1) EvtRep1.
 * This function is also used as enable check for the other event sub-types
 * (TM(5,2) to TM(5,4)).
 * @param smDesc The state machine descriptor.
 * @return The enable check result.
 */
CrFwBool_t CrPsOutCmpEvtRep1EnableCheck(FwSmDesc_t smDesc) {
  CrFwServSubType_t sevLevelIndex = CrFwOutCmpGetServSubType(smDesc)-1;
  CrPsNEvtRep_t nOfEvt = getDpEvtNOfDetectedEvtsItem(sevLevelIndex);
  nOfEvt++;
  setDpEvtNOfDetectedEvtsItem(sevLevelIndex, nOfEvt);

  CrFwBool_t enableStatus = CrFwOutRegistryIsEnabled(smDesc);
  return enableStatus;
}

/**
 * Update action of TM(5,1) EvtRep1.
 * This function is also used as update action for the other event sub-types
 * (TM(5,2) to TM(5,4)).
 *
 * Set the destination of the event report.
 * @param smDesc The state machine descriptor.
 */
void CrPsOutCmpEvtRep1UpdateAction(FwSmDesc_t smDesc) {
  CrPsEightBit_t Time[6];
  CrFwServSubType_t sevLevelIndex = CrFwOutCmpGetServSubType(smDesc)-1;
  CrFwPckt_t pckt = CrFwOutCmpGetPckt(smDesc);

  /* Update observable recording number of generated events */
  CrPsNEvtRep_t nOfGenEvt = getDpEvtNOfGenEvtRepItem(0);
  setDpEvtNOfGenEvtRepItem(sevLevelIndex, nOfGenEvt++);

  /* Update observable recording EID of last generated event */
  CrPsEvtId_t lastEvtEid = getEvtRep1EventId(pckt);
  setDpEvtLastEvtEidItem(sevLevelIndex,lastEvtEid);

  /* Update observable recording time-stamp of last generated event */
  getTmHeaderTime(pckt, &Time);
  unsigned int coarseTime = Time[0]*0x1000000 + Time[1]*0x10000 + Time[2]*0x100 + Time[3];
  unsigned int fineTime = Time[4]*0x100 + Time[5];
  CrFwTime_t lastEvtTime = (CrFwTime_t)coarseTime + (CrFwTime_t)fineTime/65536.0;
  setDpEvtLastEvtTimeItem(sevLevelIndex, lastEvtTime);

  CrFwOutCmpSetDest(smDesc, EVT_DEST);
}
