/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(5,5) EvtEnbCmd as an incoming command.
 *
 * @note This file was generated on 2018-10-28 20:42:51
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSINCMDEVTENBCMD_H_
#define CRPSINCMDEVTENBCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(5,5) EvtEnbCmd.
 * Run the procedure Start Action of Multi-EID Command of figure
 * \image html CrPsCmd5EidStart.png "Start Action of Multi-EID
 * Command"
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdEvtEnbCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(5,5) EvtEnbCmd.
 * For each valid EID found by the Start Action of the command: set the
 * corresponding element of the array isEidEnabled to true and then decrement
 * nDisabledEid x (’x’ is the severity level of the EID). Set the action
 * outcome to ’completed’.
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdEvtEnbCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSINCMDEVTENBCMD_H */
