/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TM(5,8) EvtDisIdRep as an out-going report.
 *
 * @note This file was generated on 2018-08-20 00:57:02
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSOUTCMPEVTDISIDREP_H_
#define CRPSOUTCMPEVTDISIDREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Update action of TM(5,8) EvtDisIdRep.
 * Load the list of disabled event identifiers from arrays isEidEnabled1 to
 * isEidEnabled4
 * @param smDesc The state machine descriptor.
 */
void CrPsEvtDisIdRepUpdateAction(FwSmDesc_t smDesc);

/*----------------------------------------------------------------------------*/
#endif /* CRPSOUTCMPEVTDISIDREP_H */
