/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(5,6) EvtDisIdCmd as an incoming command.
 *
 * @note This file was generated on 2018-09-29 23:48:04
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */
#ifndef CRPSINCMDEVTDISIDCMD_H_
#define CRPSINCMDEVTDISIDCMD_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"

/**
 * Start action of TC(5,6) EvtDisIdCmd.
 * Run the procedure Start Action of Multi-EID Command of figure
 * \image html CrPsCmd5EidStart.png "Start Action of Multi-EID
 * Command"
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdEvtDisIdCmdStartAction(FwSmDesc_t smDesc);

/**
 * Progress action of TC(5,6) EvtDisIdCmd.
 * For each valid EID found by the Start Action of the command: set the
 * corresponding element of the array isEidEnabled to false and then increment
 * nDisabledEid x (’x’ is the severity level of the EID). Set the action
 * outcome to ’completed’.
 * @param smDesc The state machine descriptor.
 */
void CrPsInCmdEvtDisIdCmdProgressAction(FwSmDesc_t smDesc);


/*----------------------------------------------------------------------------*/
#endif /* CRPSINCMDEVTDISIDCMD_H */
