/**
 * @file
 * @ingroup man_evt
 *
 * Implementation of TM(5,1) EvtInfoSevRep as an out-going report.
 * The header file for this implementation file (CrPsOutCmpEvtInfoSevRep.h) was
 * generated by the CORDET Editor.
 * This implementation file also implements the TM(5,2), TM(5,3) and TM(5,4)
 * reports.
 *
 */

/* Cordet Framework includes */
#include "OutRegistry/CrFwOutRegistry.h"
#include "OutCmp/CrFwOutCmp.h"

/* PUS Extension includes */
#include "CrPsOutCmpEvtInfoSevRep.h"
#include "DataPool/CrPsDpEvt.h"
#include "Pckt/CrPsPckt.h"
#include "Pckt/CrPsPcktEvt.h"
#include "CrPsConstants.h"

CrFwBool_t CrPsOutCmpEvtRep1EnableCheck(FwSmDesc_t smDesc) {
  CrFwServSubType_t sevLevelIndex = CrFwOutCmpGetServSubType(smDesc)-1;
  CrPsNEvtRep_t nOfEvt = getDpEvtNOfDetectedEvtsItem(sevLevelIndex);
  nOfEvt++;
  setDpEvtNOfDetectedEvtsItem(sevLevelIndex, nOfEvt);

  CrFwBool_t enableStatus = CrFwOutRegistryIsEnabled(smDesc);
  return enableStatus;
}

void CrPsOutCmpEvtRep1UpdateAction(FwSmDesc_t smDesc) {
  CrPsEightBit_t Time[6];
  CrFwServSubType_t sevLevelIndex = CrFwOutCmpGetServSubType(smDesc)-1;
  CrFwPckt_t pckt = CrFwOutCmpGetPckt(smDesc);

  /* Update observable recording number of generated events */
  CrPsNEvtRep_t nOfGenEvt = getDpEvtNOfGenEvtRepItem(0);
  setDpEvtNOfGenEvtRepItem(sevLevelIndex, nOfGenEvt++);

  /* Update observable recording EID of last generated event */
  CrPsEvtId_t lastEvtEid = getEvtRep1EventId(pckt);
  setDpEvtLastEvtEidItem(sevLevelIndex,lastEvtEid);

  /* Update observable recording time-stamp of last generated event */
  getTmHeaderTime(pckt, &Time);
  unsigned int coarseTime = Time[0]*0x1000000 + Time[1]*0x10000 + Time[2]*0x100 + Time[3];
  unsigned int fineTime = Time[4]*0x100 + Time[5];
  CrFwTime_t lastEvtTime = (CrFwTime_t)coarseTime + (CrFwTime_t)fineTime/65536.0;
  setDpEvtLastEvtTimeItem(sevLevelIndex, lastEvtTime);

  CrFwOutCmpSetDest(smDesc, EVT_DEST);
}
