/**
 * @file
 * @ingroup gen_cfw
 *
 * Implementation of TC(5,6) EvtDisIdCmd.
 *
 * @note This file was generated on 2018-07-25 18:43:06
 * @author Automatically Generated by CORDET Editor
 * @copyright P&P Software GmbH
 */

#include "CrPsEvtDisIdCmd.h"

/**
 * Start action of TC(5,6) EvtDisIdCmd.
 * Run the procedure Start Action of Multi-EID Command of figure
 * \image html CrPsCmd5EidStart.png "Start Action of Multi-EID
 * Command"
 * @param smDesc The state machine descriptor.
 */
void CrPsEvtDisIdCmdStartAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsEvtDisIdCmdStartAction");
   return ;
}

/**
 * Progress action of TC(5,6) EvtDisIdCmd.
 * For each valid EID found by the Start Action of the command: set the
 * corresponding element of the array isEidEnabled to false and then increment
 * nDisabledEid x (’x’ is the severity level of the EID). Set the action
 * outcome to ’completed’.
 * @param smDesc The state machine descriptor.
 */
void CrPsEvtDisIdCmdProgressAction(FwSmDesc_t smDesc)
{
   CRFW_UNUSED(smDesc);
   DBG("CrPsEvtDisIdCmdProgressAction");
   return ;
}

