/**
 * @file CrPsCmd17s3StartFunc.c
 * @ingroup Serv17
 * @ingroup procedures 
 *
 * @brief This procedure is run by the Start Action of the command (17,3)
 *
 * @author Christian Reimers <christian.reimers@univie.ac.at>
 * @author Markus Rockenbauer <markus.rockenbauer@univie.ac.at>
 * @author Alessandro Pasetti <pasetti@pnp-software.com>
 * 
 * @copyright P&P Software GmbH, 2015 / Department of Astrophysics, University of Vienna, 2018
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
 *
 */

/** CrPsCmd17s3Start function definitions */
#include "CrPsCmd17s3Start.h"
#include "CrPsServTypeId.h"
#include "DataPool/CrPsDp.h"
#include "DataPool/CrPsDpTst.h"
#include "CrPsDpTypes.h"

/** FW Profile function definitions */
#include "FwSmConstants.h"
#include "FwPrConstants.h"

/* Framework function definitions */
#include "OutFactory/CrFwOutFactory.h"
#include "OutCmp/CrFwOutCmp.h"
#include "OutLoader/CrFwOutLoader.h"

#include <stdlib.h>

/** The (17,1) command generated by the connection test command */
static FwSmDesc_t cmd;

/** The (17,4) report generated by the connection test command */
static FwSmDesc_t rep;



/* ------------------------------------------------------------------------------------ */
/* Action for node N1. */
void CrPsTestOnBoardConnectionStartN1(FwPrDesc_t prDesc) {
  CrFwDestSrc_t areYouAliveSrc;

  CRFW_UNUSED(prDesc);

  /* Set areYouAliveSrc to zero */
  areYouAliveSrc = 0;
  setDpAreYouAliveSrc(areYouAliveSrc);

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Action for node N2. */
void CrPsTestOnBoardConnectionStartN2(FwPrDesc_t prDesc) {
  CRFW_UNUSED(prDesc);

  /* Retrieve an OutComponent of type (17,1) from the OutFactory */
  cmd = CrFwOutFactoryMakeOutCmp(CR_PS_TST, CR_PS_TSTAREYOUALIVEREP, 0, 0);

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Action for node N3. */
void CrPsTestOnBoardConnectionStartN3(FwPrDesc_t prDesc) {
  CrFwCmpData_t* inData;
  CRFW_UNUSED(prDesc);

  inData = (CrFwCmpData_t*)FwPrGetData(prDesc);

  /* Generate error report OUTFACTORY_FAIL */
  CrFwRepErrKind(psOutFactoryFail, inData->typeId, inData->instanceId, CR_PS_TST, CR_PS_TSTAREYOUALIVEREP, 0);

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Action for node N4. */
void CrPsTestOnBoardConnectionStartN4(FwPrDesc_t prDesc) {
  CrFwDestSrc_t destId;
  CrFwCmpData_t* inData;
  CrFwInCmdData_t* inCmdData;
  CrFwPckt_t inPckt;

  CRFW_UNUSED(prDesc);

  /* Configure (17,1) OutComponent */

  /* Get identifier of application to which the (17,1) command must be sent.
   * This is a parameter of the (17,3) command and it must therefore be retrieved
   * from the (17.3) command. */
  inData = (CrFwCmpData_t*)FwPrGetData(prDesc);
  inCmdData = (CrFwInCmdData_t*)inData->cmpSpecificData;
  inPckt = inCmdData->pckt;
  destId = getOnBoardConnectCmdAppId(inPckt);

  /* Set out component parameters */
  CrFwOutCmpSetDest(cmd, destId);

  /* Copy the destination of the (17,1) to the data pool */
  setDpOnBoardConnectDest(destId);

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Action for node N5. */
void CrPsTestOnBoardConnectionStartN5(FwPrDesc_t prDesc) {
  CRFW_UNUSED(prDesc);

  /* Load OutComponent in OutLoader */
  CrFwOutLoaderLoad(cmd);

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Action for node N7. */
void CrPsTestOnBoardConnectionStartN7(FwPrDesc_t prDesc) {
  CrPsTstData_t* prTstData;
  CrFwCmpData_t* cmpData;
  FwSmDesc_t cmd17s3;

  /* Set outcome of Start Action to 'success' */
  prTstData = FwPrGetData(prDesc);
  cmd17s3 = prTstData->cmd17s3;
  cmpData = (CrFwCmpData_t*) FwSmGetData(cmd17s3);
  cmpData->outcome = 1;

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Action for node N8. */
void CrPsTestOnBoardConnectionStartN8(FwPrDesc_t prDesc) {
  CrPsTstData_t* prTstData;
  CrFwCmpData_t* cmpData;
  FwSmDesc_t cmd17s3;

  /* Set outcome of Start Action to 'failure' with failure code VER_REP_CR_FD */

  /* Set outcome in InCmd prData to 'failure' */
  prTstData = (CrPsTstData_t*)FwPrGetData(prDesc);
  cmd17s3 = prTstData->cmd17s3;
  cmpData = (CrFwCmpData_t*) FwSmGetData(cmd17s3);
  cmpData->outcome = 0;

  /* Set failure code to VER_REP_CR_FD */
  setDpverFailCode(VER_REP_CR_FD);

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Action for node N9. */
void CrPsTestOnBoardConnectionStartN9(FwPrDesc_t prDesc) {
  CrPsTstData_t* prTstData;

  /* Retrieve an OutComponent of type (17,4) from the OutFactory */
  rep = CrFwOutFactoryMakeOutCmp(CR_PS_TST, CR_PS_TSTCONNECTREP, 0, 0);

  /* Load the (17,4) OutComponent in the data of the Start Action Procedure.
   * This allows the (17,4) procedure to be passed to the Progress Action Procedure.
   */
  prTstData = (CrPsTstData_t*)FwPrGetData(prDesc);
  prTstData->rep17s4 = rep;

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Action for node N10. */
void CrPsTestOnBoardConnectionStartN10(FwPrDesc_t prDesc) {
  CRFW_UNUSED(prDesc);

  /* Release (17,1) OutComponent */
  CrFwOutFactoryReleaseOutCmp(cmd);

  return;
}

/* ------------------------------------------------------------------------------------ */
/* Guard on the Control Flow from DECISION1 to N1. */
FwPrBool_t CrPsTestOnBoardConnectionStartG1(FwPrDesc_t prDesc) {
  int i;
  CrFwDestSrc_t  appId, destId;

  CRFW_UNUSED(prDesc);

  /* [ Identifier of target application is legal ] */

  /* get requested target application ID */
  appId = getDpOnBoardConnectDest();

  /* get all target application IDs and check them */
  for (i=0; i<TBD; i++) {
      destId = getDpOnBoardConnectDestLstItem(i);
      if (destId == appId)
        return 1;
  }

  return 0;
}

/* ------------------------------------------------------------------------------------ */
/* Guard on the Control Flow from DECISION2 to N3. */
FwPrBool_t CrPsTestOnBoardConnectionStartG2(FwPrDesc_t prDesc) {
  CRFW_UNUSED(prDesc);

  /* [ OutFactory fails to generate OutComponent ] */
  if (cmd == NULL)
    return 1;
  else
    return 0;
}

/* ------------------------------------------------------------------------------------ */
/* Guard on the Control Flow from DECISION3 to N4. */
FwPrBool_t CrPsTestOnBoardConnectionStartG3(FwPrDesc_t prDesc) {
  CRFW_UNUSED(prDesc);

  /* [ OutFactory returns OutComponent ] */
  if (rep != NULL)
    return 1;
  else
    return 0;
}
