/**
 * \file
 *
 * Implementation of TM(17,2) TstAreYouAliveRep.
 *
 * \note This file was generated on 2018-06-10 22:43:42
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software
 */
#ifndef CRPSTSTAREYOUALIVEREP_H_
#define CRPSTSTAREYOUALIVEREP_H_

#include "CrPsConstants.h"
#include "CrPsDpTypes.h"

#include <FwSmCore.h>
#include <CrFwConstants.h>


/*----------------------------------------------------------------------------*/
#endif /* CRPSTSTAREYOUALIVEREP_H */
