/**
 * \file
 *
 * Implementation of TM(17,2) TstAreYouAliveRep.
 *
 * \note This file was generated on 2018-05-19 23:24:03
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software
 */
#ifndef CRPSSPCTSTAREYOUALIVEREP_H_
#define CRPSSPCTSTAREYOUALIVEREP_H_

#include "CrPsConstants.h"
#include "CrPsDpTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"


/*----------------------------------------------------------------------------*/
#endif /* CRPSSPCTSTAREYOUALIVEREP_H */
