/**
 * \file
 *
 * Implementation of TM(17,4) TstConnectRep.
 *
 * \note This file was generated on 2018-05-19 23:24:03
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software
 */

#include "CrPsTstConnectRep.h"

