/**
 * \file
 *
 * Implementation of TM(17,4) TstConnectRep.
 *
 * \note This file was generated on 2018-06-10 22:43:42
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software
 */
#ifndef CRPSTSTCONNECTREP_H_
#define CRPSTSTCONNECTREP_H_

#include "CrPsConstants.h"
#include "CrPsDpTypes.h"

#include <FwSmCore.h>
#include <CrFwConstants.h>


/*----------------------------------------------------------------------------*/
#endif /* CRPSTSTCONNECTREP_H */
