/**
 * \file
 *
 * Implementation of TM(17,4) TstConnectRep.
 *
 * \note This file was generated on 2018-05-19 23:24:03
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software
 */
#ifndef CRPSSPCTSTCONNECTREP_H_
#define CRPSSPCTSTCONNECTREP_H_

#include "CrPsConstants.h"
#include "CrPsDpTypes.h"

#include <FwSmCore.h>
#include <CrFwConstants.h>


/*----------------------------------------------------------------------------*/
#endif /* CRPSSPCTSTCONNECTREP_H */
