/**
 * \file
 *
 * Implementation of TM(17,2) TstAreYouAliveRep.
 *
 * \note This file was generated on 2018-06-15 19:20:43
 * \author Automatically Generated by CORDET Editor
 * \copyright P&P Software
 */
#ifndef CRPSTSTAREYOUALIVEREP_H_
#define CRPSTSTAREYOUALIVEREP_H_

#include "CrPsConstants.h"
#include "CrPsTypes.h"

#include "FwSmCore.h"
#include "CrFwConstants.h"


/*----------------------------------------------------------------------------*/
#endif /* CRPSTSTAREYOUALIVEREP_H */
